// <auto-generated />
using System;
using GymApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymApp.Domain.Attendances.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset?>("CheckedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_in_at");

                    b.Property<DateTimeOffset?>("CheckedOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_out_at");

                    b.Property<Guid>("ClientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("MarkedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("marked_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TrainingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_session_id");

                    b.HasKey("Id")
                        .HasName("pk_attendances");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_attendances_booking_id");

                    b.HasIndex("ClientUserId")
                        .HasDatabaseName("ix_attendances_client_user_id");

                    b.HasIndex("MarkedByUserId")
                        .HasDatabaseName("ix_attendances_marked_by_user_id");

                    b.HasIndex("TrainingSessionId")
                        .HasDatabaseName("ix_attendances_training_session_id");

                    b.HasIndex("TrainingSessionId", "ClientUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_attendances_training_session_id_client_user_id");

                    b.ToTable("attendances", (string)null);
                });

            modelBuilder.Entity("GymApp.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("BookedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booked_at");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid>("ClientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TrainingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_session_id");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("ClientUserId")
                        .HasDatabaseName("ix_bookings_client_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_bookings_status");

                    b.HasIndex("TrainingSessionId")
                        .HasDatabaseName("ix_bookings_training_session_id");

                    b.HasIndex("TrainingSessionId", "ClientUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_training_session_id_client_user_id")
                        .HasFilter("status IN (1, 3)");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("GymApp.Domain.Gyms.Gym", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_gyms");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_gyms_name");

                    b.ToTable("gyms", (string)null);
                });

            modelBuilder.Entity("GymApp.Domain.Gyms.GymBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_gym_branches");

                    b.HasIndex("GymId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_gym_branches_gym_id_name");

                    b.ToTable("gym_branches", (string)null);
                });

            modelBuilder.Entity("GymApp.Domain.Gyms.GymRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<Guid>("GymBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_branch_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_gym_rooms");

                    b.HasIndex("GymBranchId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_gym_rooms_gym_branch_id_name");

                    b.ToTable("gym_rooms", null, t =>
                        {
                            t.HasCheckConstraint("ck_gym_rooms_capacity_positive", "capacity > 0");
                        });
                });

            modelBuilder.Entity("GymApp.Domain.Memberships.ClientMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("MembershipPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_plan_id");

                    b.Property<decimal>("PurchasedPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("purchased_price");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("VisitLimit")
                        .HasColumnType("integer")
                        .HasColumnName("visit_limit");

                    b.Property<int>("VisitsUsed")
                        .HasColumnType("integer")
                        .HasColumnName("visits_used");

                    b.HasKey("Id")
                        .HasName("pk_client_memberships");

                    b.HasIndex("ClientUserId")
                        .HasDatabaseName("ix_client_memberships_client_user_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_client_memberships_expires_at");

                    b.HasIndex("MembershipPlanId")
                        .HasDatabaseName("ix_client_memberships_membership_plan_id");

                    b.HasIndex("ClientUserId", "Status")
                        .HasDatabaseName("ix_client_memberships_client_user_id_status");

                    b.ToTable("client_memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_client_memberships_price_non_negative", "purchased_price >= 0");

                            t.HasCheckConstraint("ck_client_memberships_valid_period", "expires_at > starts_at");

                            t.HasCheckConstraint("ck_client_memberships_visit_limit_positive", "visit_limit IS NULL OR visit_limit > 0");

                            t.HasCheckConstraint("ck_client_memberships_visits_used_non_negative", "visits_used >= 0");

                            t.HasCheckConstraint("ck_client_memberships_visits_within_limit", "visit_limit IS NULL OR visits_used <= visit_limit");
                        });
                });

            modelBuilder.Entity("GymApp.Domain.Memberships.MembershipPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsUnlimited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unlimited");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<int?>("VisitLimit")
                        .HasColumnType("integer")
                        .HasColumnName("visit_limit");

                    b.HasKey("Id")
                        .HasName("pk_membership_plans");

                    b.HasIndex("GymId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_membership_plans_gym_id_name");

                    b.ToTable("membership_plans", null, t =>
                        {
                            t.HasCheckConstraint("ck_membership_plans_duration_positive", "duration_days > 0");

                            t.HasCheckConstraint("ck_membership_plans_price_non_negative", "price >= 0");

                            t.HasCheckConstraint("ck_membership_plans_visit_limit_positive", "visit_limit IS NULL OR visit_limit > 0");
                        });
                });

            modelBuilder.Entity("GymApp.Domain.Schedule.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("GymBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_branch_id");

                    b.Property<Guid>("GymRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_room_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TrainerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainer_profile_id");

                    b.Property<Guid>("TrainingTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("training_type_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_training_sessions");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_training_sessions_status");

                    b.HasIndex("GymRoomId", "StartsAt")
                        .HasDatabaseName("ix_training_sessions_gym_room_id_starts_at");

                    b.HasIndex("TrainerProfileId", "StartsAt")
                        .HasDatabaseName("ix_training_sessions_trainer_profile_id_starts_at");

                    b.HasIndex("TrainingTypeId", "StartsAt")
                        .HasDatabaseName("ix_training_sessions_training_type_id_starts_at");

                    b.ToTable("training_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_training_sessions_capacity_positive", "capacity > 0");

                            t.HasCheckConstraint("ck_training_sessions_valid_period", "ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("GymApp.Domain.Schedule.TrainingType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("DefaultCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("default_capacity");

                    b.Property<int>("DefaultDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("default_duration_minutes");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<Guid>("GymId")
                        .HasColumnType("uuid")
                        .HasColumnName("gym_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_training_types");

                    b.HasIndex("GymId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_training_types_gym_id_name");

                    b.ToTable("training_types", null, t =>
                        {
                            t.HasCheckConstraint("ck_training_types_capacity_positive", "default_capacity IS NULL OR default_capacity > 0");

                            t.HasCheckConstraint("ck_training_types_duration_positive", "default_duration_minutes > 0");
                        });
                });

            modelBuilder.Entity("GymApp.Domain.Trainers.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_specializations");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_specializations_name");

                    b.ToTable("specializations", (string)null);
                });

            modelBuilder.Entity("GymApp.Domain.Trainers.TrainerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_years");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_trainer_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_trainer_profiles_user_id");

                    b.ToTable("trainer_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_trainer_profiles_experience_years", "experience_years >= 0");
                        });
                });

            modelBuilder.Entity("GymApp.Domain.Trainers.TrainerSpecialization", b =>
                {
                    b.Property<Guid>("TrainerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainer_profile_id");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("uuid")
                        .HasColumnName("specialization_id");

                    b.HasKey("TrainerProfileId", "SpecializationId")
                        .HasName("pk_trainer_specializations");

                    b.HasIndex("SpecializationId")
                        .HasDatabaseName("ix_trainer_specializations_specialization_id");

                    b.ToTable("trainer_specializations", (string)null);
                });

            modelBuilder.Entity("GymApp.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymApp.Domain.Attendances.Attendance", b =>
                {
                    b.HasOne("GymApp.Domain.Bookings.Booking", null)
                        .WithOne("Attendance")
                        .HasForeignKey("GymApp.Domain.Attendances.Attendance", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attendances_bookings_booking_id");

                    b.HasOne("GymApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendances_asp_net_users_client_user_id");

                    b.HasOne("GymApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("MarkedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attendances_asp_net_users_marked_by_user_id");

                    b.HasOne("GymApp.Domain.Schedule.TrainingSession", null)
                        .WithMany("Attendances")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendances_training_sessions_training_session_id");
                });

            modelBuilder.Entity("GymApp.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("GymApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_asp_net_users_client_user_id");

                    b.HasOne("GymApp.Domain.Schedule.TrainingSession", null)
                        .WithMany("Bookings")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_training_sessions_training_session_id");
                });

            modelBuilder.Entity("GymApp.Domain.Gyms.GymBranch", b =>
                {
                    b.HasOne("GymApp.Domain.Gyms.Gym", "Gym")
                        .WithMany("Branches")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gym_branches_gyms_gym_id");

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("GymApp.Domain.Gyms.GymRoom", b =>
                {
                    b.HasOne("GymApp.Domain.Gyms.GymBranch", "GymBranch")
                        .WithMany("Rooms")
                        .HasForeignKey("GymBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gym_rooms_gym_branches_gym_branch_id");

                    b.Navigation("GymBranch");
                });

            modelBuilder.Entity("GymApp.Domain.Memberships.ClientMembership", b =>
                {
                    b.HasOne("GymApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ClientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_client_memberships_asp_net_users_client_user_id");

                    b.HasOne("GymApp.Domain.Memberships.MembershipPlan", null)
                        .WithMany("ClientMemberships")
                        .HasForeignKey("MembershipPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_client_memberships_membership_plans_membership_plan_id");
                });

            modelBuilder.Entity("GymApp.Domain.Memberships.MembershipPlan", b =>
                {
                    b.HasOne("GymApp.Domain.Gyms.Gym", "Gym")
                        .WithMany("MembershipPlans")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_membership_plans_gyms_gym_id");

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("GymApp.Domain.Schedule.TrainingSession", b =>
                {
                    b.HasOne("GymApp.Domain.Gyms.GymRoom", "GymRoom")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("GymRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_training_sessions_gym_rooms_gym_room_id");

                    b.HasOne("GymApp.Domain.Trainers.TrainerProfile", "TrainerProfile")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("TrainerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_training_sessions_trainer_profiles_trainer_profile_id");

                    b.HasOne("GymApp.Domain.Schedule.TrainingType", "TrainingType")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("TrainingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_training_sessions_training_types_training_type_id");

                    b.Navigation("GymRoom");

                    b.Navigation("TrainerProfile");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("GymApp.Domain.Schedule.TrainingType", b =>
                {
                    b.HasOne("GymApp.Domain.Gyms.Gym", "Gym")
                        .WithMany("TrainingTypes")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_training_types_gyms_gym_id");

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("GymApp.Domain.Trainers.TrainerProfile", b =>
                {
                    b.HasOne("GymApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("GymApp.Domain.Trainers.TrainerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trainer_profiles_asp_net_users_user_id");
                });

            modelBuilder.Entity("GymApp.Domain.Trainers.TrainerSpecialization", b =>
                {
                    b.HasOne("GymApp.Domain.Trainers.Specialization", "Specialization")
                        .WithMany("Trainers")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trainer_specializations_specializations_specialization_id");

                    b.HasOne("GymApp.Domain.Trainers.TrainerProfile", "TrainerProfile")
                        .WithMany("Specializations")
                        .HasForeignKey("TrainerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trainer_specializations_trainer_profiles_trainer_profile_id");

                    b.Navigation("Specialization");

                    b.Navigation("TrainerProfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GymApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GymApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("GymApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GymApp.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("GymApp.Domain.Bookings.Booking", b =>
                {
                    b.Navigation("Attendance")
                        .IsRequired();
                });

            modelBuilder.Entity("GymApp.Domain.Gyms.Gym", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("MembershipPlans");

                    b.Navigation("TrainingTypes");
                });

            modelBuilder.Entity("GymApp.Domain.Gyms.GymBranch", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("GymApp.Domain.Gyms.GymRoom", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("GymApp.Domain.Memberships.MembershipPlan", b =>
                {
                    b.Navigation("ClientMemberships");
                });

            modelBuilder.Entity("GymApp.Domain.Schedule.TrainingSession", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("GymApp.Domain.Schedule.TrainingType", b =>
                {
                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("GymApp.Domain.Trainers.Specialization", b =>
                {
                    b.Navigation("Trainers");
                });

            modelBuilder.Entity("GymApp.Domain.Trainers.TrainerProfile", b =>
                {
                    b.Navigation("Specializations");

                    b.Navigation("TrainingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
